### ISSUE TITLE
Create a footer

### ISSUE THREAD

**Issue by DanielRomeo** [DanielRomeo/JackScriptDocs#3]
Create a footer component and add it to the project. When completed,` npm run build` the project. and Create a PR.
You can use any style you want, you can add any contents to the footer you want. 

Requirements:
1. The footer must have a GitHub icon linked to https://github.com/danielromeo/jackscript-py. 

To contribute to this Issue; read the README.md and the contribution.md files

**Comment by Drallas** [comment]
Sounds interesting, i'm new to react and Typescript. 
I guess i first build it as is to see how the footer should fit in!

**Comment by DanielRomeo** [comment]
okay. Im going to assign you. Try it out and make a Pull request when you think you did an OK job. if not, no worries..
goodluck

**Comment by Drallas** [comment]
Ok it's done.. first time using React, only watched some Net Ninja Tutorial.  But diving into code is the best learning accelerator.  :)

**Comment by DanielRomeo** [comment]
Your changes have been merged... Ill update the website in 12 hours time. great work

**Comment by DanielRomeo** [comment]
> Ok it's done.. first time using React, only watched some Net Ninja Tutorials. But diving into code is the best learning accelerator. :)

Definitely... Best way to learn is to actually do it yourself

**Comment by DanielRomeo** [comment]
Dont forget to **star** the project :)

**Comment by Drallas** [comment]
Thx for the opportunity!
